# Generated by Django 6.0.3 on 2026-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(help_text='Comma-separated categories', max_length=255)),
            ],
        ),
    ]
